"""initial schema

Revision ID: 356a74860b42
Revises: 
Create Date: 2026-06-26 00:53:42.028779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '356a74860b42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('last_active_date', sa.DateTime(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.discord_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'member_id', name='uq_event_member')
    )
    op.create_table('disciplinary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_history_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.Column('recorded_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_history_entries')
    op.drop_table('disciplinary_records')
    op.drop_table('attendance_records')
    op.drop_table('settings')
    op.drop_table('members')
    op.drop_table('events')
    # ### end Alembic commands ###
