"""add award types and member awards

Revision ID: 59f9dfc8cccd
Revises: 356a74860b42
Create Date: 2026-06-26 01:06:00.002405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59f9dfc8cccd'
down_revision: Union[str, None] = '356a74860b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('member_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('award_type_id', sa.Integer(), nullable=False),
    sa.Column('date_awarded', sa.DateTime(), nullable=True),
    sa.Column('awarded_by', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['award_type_id'], ['award_types.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.discord_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'award_type_id', name='uq_member_award')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_awards')
    op.drop_table('award_types')
    # ### end Alembic commands ###
