"""add guild config, ranks, and companies

Revision ID: 968dc573a738
Revises: 59f9dfc8cccd
Create Date: 2026-06-29 05:07:12.853942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '968dc573a738'
down_revision: Union[str, None] = '59f9dfc8cccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('guild_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regiment_name', sa.String(), nullable=False),
    sa.Column('regiment_motto', sa.String(), nullable=True),
    sa.Column('brand_color', sa.Integer(), nullable=False),
    sa.Column('inactivity_days_threshold', sa.Integer(), nullable=False),
    sa.Column('admin_role_id', sa.BigInteger(), nullable=True),
    sa.Column('officer_role_id', sa.BigInteger(), nullable=True),
    sa.Column('recruiter_role_id', sa.BigInteger(), nullable=True),
    sa.Column('member_role_id', sa.BigInteger(), nullable=True),
    sa.Column('candidate_role_id', sa.BigInteger(), nullable=True),
    sa.Column('visitor_role_id', sa.BigInteger(), nullable=True),
    sa.Column('inactive_role_id', sa.BigInteger(), nullable=True),
    sa.Column('recruitment_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('personnel_forum_id', sa.BigInteger(), nullable=True),
    sa.Column('roster_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('mod_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('announcements_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('welcome_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranks')
    op.drop_table('guild_config')
    op.drop_table('companies')
    # ### end Alembic commands ###
