"""add loa_until to member and billboard channel to guild config

Revision ID: c4561240bcd2
Revises: 968dc573a738
Create Date: 2026-07-01 00:34:45.358403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4561240bcd2'
down_revision: Union[str, None] = '968dc573a738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('billboard_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('members', sa.Column('loa_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'loa_until')
    op.drop_column('guild_config', 'billboard_channel_id')
    # ### end Alembic commands ###
